### ISSUE TITLE
SSL certificate?

### ISSUE THREAD

**Issue by sasadjolic** [ForestAdmin/forest-doc#38]
I have SSL enabled on a custom domain in my project. When I go to that custom domain in the browser, I'm seeing an invalid SSL cert browser error. This is due to the certificate not having been signed for our specific custom domain. It looks like a generic Forest SSL cert is being used instead. Is there a way to use Let's Encrypt on our custom Forest domain to have the SSL cert match our domain?

**Comment by louisteenbrink** [comment]
@sasadjolic Forest is adapting to your application protocol following the url provided in your environments settings. To setup HTTPS on Forest, simply provide a https application url in your environments settings :)
